
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3001:3000
    volumes:
      - ./config:/app/config   # adjust to your Homepage config path
    restart: unless-stopped
    depends_on:
      - line2-proxy

  line2-proxy:
    build: ./line2-proxy
    container_name: line2-proxy
    ports:
      - 3000:3000
    restart: unless-stopped
